(** The interface which any routing agent must implement *)
class type t = 
object

  method mac_recv_l3pkt : L3pkt.t -> unit
    (** This method will be called whenever a packet arrives from the MAC layer.*)

  method mac_recv_l2pkt : L2pkt.t -> unit
    (** Same as {!Rt_agent_base.mac_recv_l3pkt}, except that the packet comes
      with L2 hdr still on, for those agents which might need it. *)

  method app_recv_l4pkt : L4pkt.t -> dst:Common.nodeid_t -> unit
    (** This method is called whenever a packet is generated by an
      application-layer agent. *)

end
