(*
 *
 *  NAB - Network in a Box
 *  Henri Dubois-Ferriere, LCA/LCAV, EPFL
 * 
 *  Copyright (C) 2004 Laboratory of Audiovisual Communications (LCAV), and
 *  Laboratory for Computer Communications and Applications (LCA), 
 *  Ecole Polytechnique Federale de Lausanne (EPFL),
 *  CH-1015 Lausanne, Switzerland
 *
 *  This file is part of NAB. NAB is free software; you can redistribute it 
 *  and/or modify it under the terms of the GNU General Public License as 
 *  published by the Free Software Foundation; either version 2 of the License,
 *  or (at your option) any later version. 
 *
 *  NAB is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 *  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 *  details (enclosed in the file GPL). 
 *
 *)

(* $Id$ *)



(** Routing Agent interface.
 
  @author Henri Dubois-Ferriere.
 *)

(** The interface which a routing agent must implement.
  
  Note for those implementing a routing agent: it is simplest to inherit
  from {!Rt_agent_base.base}, for the reasons described therein.
*)
class type t = 
object

  inherit Log.inheritable_loggable 
  method myid : Common.nodeid_t
    (** Returns the id of the node to which this agent is attached. *)

  method recv_pkt_mac : 
    l2src:Common.nodeid_t -> l2dst:Common.nodeid_t -> L3pkt.t -> unit
    (** This method will be called whenever a packet arrives from the MAC
      layer, passing as paremeters the node which transmitted the packet
      ([l2src]), the destination node of the packet ([l2dst]), and the layer 3
      packet.*)

  method recv_pkt_app : L4pkt.t -> Common.nodeid_t -> unit
    (** This method is called with outbound packets generated by upper-layer
      (application) agents or traffic sources.*)

  method mac_callback : L3pkt.t -> Common.nodeid_t -> unit
    (** This method may be called by MAC layers (those which support it) to
      notify the upper layer routing agent when a transmitting a packet
      to a next hop has failed. The callback is provided with the l3 packet
      which could not be forwarded, and the node_id to which forwarding
      failed. *)

end
